########################################################################
#                           Test definition                            #
########################################################################

# list of Gemfiles associated with tools to be tested
gemfile:
  - www/board/agenda/Gemfile

# platforms to test on
os:
  - osx
  - linux
dist: trusty

########################################################################
#                           VM Configuration                           #
########################################################################

# Ruby version 2.4.0 (see comments as to why not 2.4.1)
language: ruby
rvm: # http://rubies.travis-ci.org/
  - 2.4
  - 2.5

# Skip Ruby 2.4 on OS/X due to occasional hangs and
# https://github.com/travis-ci/travis-ci/issues/7848
matrix:
  exclude:
  - rvm: 2.4
    os: osx

# add subversion on Linux
addons:
  apt:
    packages:
    - subversion

# install recent Node.js
before_install:
  - nvm install 7

  # Workaround for https://github.com/travis-ci/travis-ci/issues/8969
  - gem update --system

# configure ASF LDAP
sudo: required
before_script:
  - rvmsudo ruby -I $PWD/lib -r whimsy/asf -e "ASF::LDAP.configure"

########################################################################
#                             Notification                             #
########################################################################

# where to send notifications
notifications:
  # https://issues.apache.org/jira/browse/INFRA-11080
  # https://github.com/apache/infrastructure-puppet/pull/319
  email:
  - travis@whimsy-vm4.apache.org
